/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MotorA_Dir.h"
#include "UART.h"
#include "MotorPWM_aliases.h"
#include "MotorPWM.h"
#include "MotorA_PWM.h"
#include "MotorCW_aliases.h"
#include "MotorCW.h"
#include "usCounter.h"
#include "Clock_3.h"
#include "MotorA_ISR.h"
#include "Encoder_aliases.h"
#include "Encoder.h"
#include "MotorA_QuadDec.h"
#include "MotorCCW_aliases.h"
#include "MotorCCW.h"
#include "ServoAB.h"
#include "ServoA_Out_aliases.h"
#include "ServoA_Out.h"
#include "Clock_4.h"
#include "Servo_PWM.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "ServoB_Out_aliases.h"
#include "ServoB_Out.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "UART_IntClock.h"
#include "MotorA_QuadDec_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

